server:
  port: 11111

logging:
  config: classpath:log4j2-spring.yml

# 多环境配置文件激活属性
spring:
  profiles:
    active: dev

wjy:
  hello: helloWorld!
  number: ${random.int}
  msg: hi! WJY! ${wjy.hello} ${wjy.number}